#!/usr/bin/env python3
"""Export the validator's data-driven rules as JSON. Stdlib only.

Three places enforce the same submission rules: this repository's CI
(`scripts/validate.py`, the authority), the storefront's upload endpoint,
and the Personal Jarvis app at install time. Rules copied by hand into
three languages drift, and drift here has a specific ugly shape — the
endpoint accepts a submission, opens a pull request, and CI then rejects
it, leaving the author with a "published" confirmation and a pull request
that never merges.

So the parts of the rule set that are *data* — limits, patterns, reserved
names, allowlists — are generated from `validate.py` into `rules.json`
and published alongside `index.json`. Consumers read that file instead of
retyping the values. The parts that are *logic* (manifest shape, the MCP
server checks) still have to be implemented per language; `validate.py`
remains the authority for those.

Regex patterns are written in a syntax both Python's `re` and ECMAScript
accept, so a consumer can use them verbatim.

Usage:
    python scripts/export_rules.py            # write rules.json
    python scripts/export_rules.py --check    # fail if rules.json is stale
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RULES_PATH = ROOT / "rules.json"


def load_validator():
    spec = importlib.util.spec_from_file_location("validate", ROOT / "scripts" / "validate.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def build_rules() -> dict:
    v = load_validator()
    return {
        "$comment": (
            "GENERATED by scripts/export_rules.py from scripts/validate.py — do not edit by "
            "hand. Patterns are valid in both Python re and ECMAScript. validate.py stays the "
            "authority: this file carries the data-driven rules only, not the manifest-shape "
            "or MCP-server logic."
        ),
        "generated_from": "scripts/validate.py",
        "limits": {
            "max_file_bytes": v.MAX_FILE_BYTES,
            "max_skill_bytes": v.MAX_SKILL_BYTES,
            "max_bundled_skills": v.MAX_BUNDLED_SKILLS,
            "max_description_chars": v.MAX_DESCRIPTION_CHARS,
            "max_wallpaper_bytes": v.MAX_WALLPAPER_BYTES,
            "max_wallpaper_title_chars": v.MAX_WALLPAPER_TITLE_CHARS,
        },
        "patterns": {
            "name": v.NAME_RE.pattern,
            "github_login": v.GITHUB_LOGIN_RE.pattern,
            "semver": v.SEMVER_RE.pattern,
            "env_placeholder": v.ENV_PLACEHOLDER_RE.pattern,
            "header_placeholder": v.HEADER_PLACEHOLDER_RE.pattern,
            "token_literal": v.TOKEN_LITERAL_RE.pattern,
            "npm_pin": v.NPM_PIN_RE.pattern,
            "pypi_pin": v.PYPI_PIN_RE.pattern,
            "image_tag": v.IMAGE_TAG_RE.pattern,
            "image_digest": v.IMAGE_DIGEST_RE.pattern,
            "env_name": v.ENV_NAME_RE.pattern,
        },
        "forbidden_name_substrings": ["--", ".."],
        "secret_patterns": [pattern.pattern for pattern in v.SECRET_PATTERNS],
        "reserved": {
            "plugin_ids": sorted(v.RESERVED_PLUGIN_IDS),
            "skill_names": sorted(v.RESERVED_SKILL_NAMES),
            # Variables a manifest may not set: they decide what runs before
            # the plugin's own first line does.
            "env_names": sorted(v.RESERVED_ENV_NAMES),
        },
        "stdio_launchers": sorted(v.STDIO_LAUNCHERS),
        # The options each launcher may carry before its package
        # specification. Everything after that belongs to the server the
        # publisher wrote and is not checked. `docker_value` options take a
        # bare variable NAME as their value.
        "stdio_flags": {
            "npx": sorted(v.NPX_FLAGS),
            "uvx": sorted(v.UVX_FLAGS),
            "docker": sorted(v.DOCKER_FLAGS),
            "docker_value": sorted(v.DOCKER_VALUE_FLAGS),
        },
        "auth_modes": sorted(v.AUTH_MODES),
        "wallpaper_licenses": sorted(v.WALLPAPER_LICENSES),
        "plugin_schema": v.PLUGIN_SCHEMA,
        "extension_namespace": v.EXTENSION_NAMESPACE,
    }


def serialize(rules: dict) -> str:
    return json.dumps(rules, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when rules.json does not match validate.py",
    )
    args = parser.parse_args()

    expected = serialize(build_rules())

    if args.check:
        actual = RULES_PATH.read_text(encoding="utf-8") if RULES_PATH.exists() else ""
        if actual != expected:
            print(
                "FAIL — rules.json is out of date with scripts/validate.py.\n"
                "Run: python scripts/export_rules.py"
            )
            return 1
        print("OK — rules.json matches validate.py")
        return 0

    RULES_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {RULES_PATH.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
